name: drizzlepac
channels:
    - defaults
dependencies:
    - python
    - setuptools
    - numpy
    - numpydoc
    - scipy
    - astropy
    - graphviz
    - pip:
      - -e ..
      - sphinx
      - sphinx_rtd_theme
      - sphinx_automodapi
      - matplotlib
      - "spherical_geometry>=1.2.22"
      - fitsblender
      - nictools
      - pyregion
      - stwcs
      - stsci.tools
      - "stsci.image>=2.3.0"
      - stsci.imagestats
      - stsci.skypac
      - stsci.stimage
      - "tweakwcs>=0.8.0"
      - stregion
      - astroquery
      - photutils
      - lxml
      - tables
