name: drizzlepac
channels:
    - defaults
dependencies:
    - "python>=3.5"
    - setuptools
    - numpy
    - numpydoc
    - scipy
    - "astropy>=3.1"
    - graphviz
    - pip:
      - sphinx
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
      - matplotlib
      - spherical_geometry
      - fitsblender
      - nictools
      - pyregion
      - stwcs
      - spherical-geometry
      - stsci.tools
      - stsci.convolve
      - "stsci.image>=2.3.0"
      - stsci.imagemanip
      - stsci.imagestats
      - stsci.skypac
      - stsci.stimage
      - "tweakwcs>=0.3.3"
      - stregion
      - astroquery
      - photutils
      - pysynphot
      - lxml
