name: drizzlepac
channels:
    - http://ssb.stsci.edu/astroconda
    - conda-forge
dependencies:
    - python=3.5
    - numpy
    - scipy
    - numpydoc
    - graphviz
    - matplotlib
    - astropy
    - fitsblender
    - nictools
    - pyregion
    - stwcs
    - spherical-geometry
    - stsci.tools
    - stsci.convolve
    - stsci.image>=2.3.0
    - stsci.imagemanip
    - stsci.imagestats
    - stsci.ndimage
    - stsci.skypac
    - stsci.stimage
    - stwcs
    - tweakwcs>=0.3.3
    - stregion
    - sphinx
    - astroquery
    - photutils
    - pysynphot
    - lxml
    - pip:
      - sphinx_rtd_theme
      - git+https://github.com/spacetelescope/stsci_rtd_theme.git#egg=stsci_rtd_theme
      - sphinx_automodapi
